name: kemo_news_app

description: "An advanced Flutter project with Firebase, SQLite, and multimedia support, tailored for news, events, and projects."

publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database dependencies
  path: ^1.9.0                  # Работа с файловыми путями
  path_provider: ^2.1.2         # Доступ к файловой системе
  sqflite: ^2.2.8+4             # Локальная база данных SQLite
  crypto: ^3.0.3                # Хеширование данных
  csv: ^6.0.0                   # Работа с CSV файлами
  shared_preferences: ^2.2.2    # Локальное хранение данных
  intl: ^0.20.1                 # Работа с датами и форматированием
  image_picker: ^1.1.2          # Выбор изображений из галереи/камеры
  cached_network_image: ^3.3.1  # Кэширование изображений
  video_player: ^2.8.2          # Воспроизведение видео
  package_info_plus: ^8.1.2     # Информация о приложении
  flutter_local_notifications: ^18.0.1  # Обновленная версия уведомлений
  

  # Firebase dependencies
  cloud_firestore: ^5.6.0       # Firebase Firestore
  firebase_core: ^3.9.0         # Firebase инициализация
  firebase_auth: ^5.3.4         # Firebase аутентификация
  firebase_messaging: ^15.1.6   # Уведомления Firebase
  firebase_storage: ^12.3.7

  # Логирование
  logger: ^2.0.2                # Логирование для отладки

  # WebView для отображения веб-контента
  webview_flutter: ^4.10.0

  # Cupertino иконки для iOS-стиля
  cupertino_icons: ^1.0.8

  # HTTP для сетевых запросов
  http: ^1.2.1

  # Открытие URL-адресов
  url_launcher: ^6.3.0

  # Управление состоянием
  provider: ^6.1.2              # Управление состоянием

  # Время
  timezone: ^0.10.0            # Работа с часовыми поясами

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2

  # Анализатор кода для Flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Подключение мультимедиа
  assets:
    - assets/video/charity_video.mp4
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

plugin:
  platforms:
    linux: false  # Отключаем поддержку Linux для flutter_local_notifications
