// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL6quxbRcf9HMZmX3eES_CA9ZuhOo1ZdA',
    appId: '1:543037758825:web:435506b69ef252890571f8',
    messagingSenderId: '543037758825',
    projectId: 'kemo-app-b6072',
    authDomain: 'kemo-app-b6072.firebaseapp.com',
    storageBucket: 'kemo-app-b6072.firebasestorage.app',
    measurementId: 'G-HWYF9Y9LZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq50wCIzXYaEmc6e3RS3KhUDEzvgbygcA',
    appId: '1:543037758825:android:6457aba35146b9310571f8',
    messagingSenderId: '543037758825',
    projectId: 'kemo-app-b6072',
    storageBucket: 'kemo-app-b6072.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADRnhGYRCHkd1GLn6a75Zc2cLj4RQMmBM',
    appId: '1:543037758825:ios:5dfe7600a8864ff00571f8',
    messagingSenderId: '543037758825',
    projectId: 'kemo-app-b6072',
    storageBucket: 'kemo-app-b6072.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADRnhGYRCHkd1GLn6a75Zc2cLj4RQMmBM',
    appId: '1:543037758825:ios:5dfe7600a8864ff00571f8',
    messagingSenderId: '543037758825',
    projectId: 'kemo-app-b6072',
    storageBucket: 'kemo-app-b6072.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL6quxbRcf9HMZmX3eES_CA9ZuhOo1ZdA',
    appId: '1:543037758825:web:29fbb3481f91b8e90571f8',
    messagingSenderId: '543037758825',
    projectId: 'kemo-app-b6072',
    authDomain: 'kemo-app-b6072.firebaseapp.com',
    storageBucket: 'kemo-app-b6072.firebasestorage.app',
    measurementId: 'G-SD3QSJ0W0C',
  );
}
